language: python

env:
  - BUILD_IMAGE="qpylib"
  - BUILD_TAG="build"
  - BUILD_GIT_NAME="IBM"
  - BUILD_GIT_EMAIL="<>" # Intentionally empty

services:
  - docker

before_install:
  - docker build -t "${BUILD_IMAGE}":"${BUILD_TAG}" .

stages:
  - lint
  - test
  - name: build-development
    if: env(QPYLIB_TAG) IS blank
  - name: build-release
    if: env(QPYLIB_TAG) IS present

jobs:
  include:
    - stage: lint
      script:
        - ./lint.sh "${BUILD_IMAGE}:${BUILD_TAG}"
    - stage: test
      script:
        - ./test.sh "${BUILD_IMAGE}:${BUILD_TAG}"
    - stage: build-development
      script:
        - ./build.sh "${TRAVIS_COMMIT}-dev" "${BUILD_IMAGE}:${BUILD_TAG}"
    - stage: build-release
      script:
        - ./build.sh "${TRAVIS_TAG}" "${BUILD_IMAGE}:${BUILD_TAG}"
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "${BUILD_GIT_NAME}"
        - git config --local user.email "${BUILD_GIT_EMAIL}"
        - export TRAVIS_TAG="${QPYLIB_TAG}"
        - git tag "${TRAVIS_TAG}"
      deploy:
        provider: releases
        api_key: "${GITHUB_OAUTH_TOKEN}"
        file: "dist/qpylib-${TRAVIS_TAG}.tar.gz"
        skip_cleanup: true
        on:
          all_branches: true